title: OPL
tagline: Runtime and Viewer for EPOC Programs and Files
copyright: Copyright © 2021-2022 Jason Morley, Tom Sutcliffe
baseurl: ""
url: ""

plugins:
  - jekyll-feed

defaults:
  - values:
      layout: "default"
